#!/bin/sh
# ** requires maim **

# screenshot folder
IMG_FOLDER=$HOME/Pictures/Screenshots

IMG_PATH=$IMG_FOLDER/pic-full-"$(date '+%y%m%d-%H%M-%S').png"

# maim default mod, take fullscreen screenshot, save it to IMG_PATH
maim $IMG_PATH 

# copy IMG to clipboard, you can paste it to x11 applications use C-V etc.
xclip -selection clipboard $IMG_PATH -t image/png

